var my = {
    Save: "Simpan",
    "Save all": "Simpan semua",
    Rename: "Namakan semula",
    Open: "Buka",
    Edit: "Edit",
    Delete: "Padam",
    Folder: "Folder",
    "Add New": "Tambah baru",
    Size: "Saiz",
    Date: "Tarikh",
    "back to parent folder": "kembali ke folder induk",
    Download: "Muat turun",
    Type: "Jenis",
    Information: "Maklumat",
    Files: "Fail",
    Table: "Jadual",
    Cards: "Kad",
    Total: "Jumlah",
    "Are you sure ?": "Adakah anda pasti ?",
    Details: "Butiran",
    "Enter a new name": "Masukkan nama baharu",
    Add: "Tambah",
    "Select something": "Pilih sesuatu",
    "Download file": "Muat turun fail",
    Preview: "Pratonton",
    Refresh: "Refresh",
    "Are you sure you want to exit without saving?": "Adakah anda pasti mahu keluar tanpa menyimpan?",
    "Save before closing?": "Simpan sebelum tutup?",
    Copy: "Salin",
    Cut: "Potong",
    Paste: "Tampal",
    "Deleting...": "Memadam...",
    "Copying...": "Menyalin...",
    "Moving...": "Memindahkan...",
    Folders: "Folders",
    "Search results": "Hasil carian",
    "Search results in": "Hasil carian dalam",
    "Search files and folders": "Cari fail dan folder",
    "Add new file": "Tambah file baharu",
    "Add new folder": "Tambah folder baharu",
    "Upload file": "Muat naik fail",
    folder: "folder",
    file: "fail",
    archive: "arkib",
    audio: "audio",
    image: "imej",
    video: "video",
    code: "kod",
    document: "dokumen",
    of: "daripada",
    used: "digunakan",
    "Open item location": "Buka lokasi item",
    "Are you sure you want to delete": "Adakah anda pasti ingin memadam",
    "these items:": "item-item ini:",
    "this item:": "item ini:",
    "Delete files": "Padam file",
    and: "dan",
    "more file(s)": "lebih banyak fail",
    "Close the editor": "Tutup editor",
    "Close this file": "Tutup file",
    "Owner": "Pemilik",
    "Permissions": "Kebenaran",
    "Change Permissions": "Tukar Kebenaran",
    "Set": "Tetapkan",
    "Extract": "Ekstrak",
    "Extract directory": "Ekstrak direktori",
    "Extracting...": "Mengekstraksi...",
    "Compress": "Mampatkan",
    "Compressing...": "Memampatkan...",
};